# -*- coding: utf-8 -*-
"""Amazon Sale Report 11_March_25

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16PfWlVv-85W4AHcHk6oTfB-vwjmg6nsl
"""

!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install seaborn

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

df = pd.read_csv('/Amazon Sale Report.csv',encoding='unicode_escape')

from google.colab import drive
drive.mount('/content/drive')

df.shape

df.head()

df.tail()

df.info()

#drop unrelated/blank columns
df.drop(['New','Pendings'],axis=1,inplace=True)

df.info()

pd.isnull(df)
# checking null value

pd.isnull(df).sum()
# sum will give total values of null values

df.shape

#drop null values
df.dropna(inplace=True)

df.shape

df.columns

#change data type
df['ship-postal-code']=df['ship-postal-code'].astype(int)

#checking whether the data type change or not
df['ship-postal-code'].dtype

df['Date']=pd.to_datetime(df['Date'])

df.info()

df.columns

#rename columns
df.rename(columns={'Qty':'Quantity'})

#describe() method return description of the data in the dataframe(i.e count,mean,std,min..etc)
df.describe()

df.describe(include='object')

#use describe() for specific columns
df[['Qty','Amount']].describe()

"""EDA"""

df.columns

"""Size"""

ax=sns.countplot(x='Size',data=df)

ax=sns.countplot(x='size',data=df)

for bars in ax.containers:
  ax.bar_label(bars)

"""Note: From above graph you can see that most of the people buys M-size

# **Group By**

The groupby() function in pandas is used to group data based on one or more columns in a dataframe
"""

df.groupby(['size'],as_index=False)['Qty'].sum().sort_values(by='Qty',ascending=False)

S_Qty=df.groupby(['size'],as_index=False)['Qty'].sum().sort_values(by='Qty',ascending=False)

sns.barplot(x='size',y='Qty',data=S_Qty)

"""Note: From above graph you can see that most of the Qty buys M-size in the sales

**Courier** **Status**
"""

sns.countplot(data=df, x='Courier Status',hue= 'Status')

plt.figure(figsize=(10,5))
ax=sns.countplot(data=df, x='Courier Status',hue= 'Status')

plt.show()

"""Note : from above graph the majority of the orders are shipped through the courier."""

#histogram
df['Size'].hist()

df['Category'] = df['Category'].astype(str)
column_data = df['Category']
plt.figure(figsize=(10,5))
plt.hist(column_data, bins=30, edgecolor='Black')
plt.xticks(rotation=90)
plt.show()

"""Note: from above graph you can see that most of the buyers are T-shirt"""

#checking B2B Data by using pie chart
 B2B_Check = df['B2B'].value_counts()

 #plot the pie chart
 plt.pie(B2B_Check.values,labels=B2B_Check.index,autopct='%1.2f%%')
 plt.show()

#checking B2B Data by using pie chart
B2B_Check = df['B2B'].value_counts()

#plot the pie chart
plt.pie(B2B_Check.values,labels=B2B_Check.index,autopct='%1.2f%%')
plt.show()

"""Note: From above chart we can see that maximum i.e. 99.3% of buyers are retailers and 0.8% are B2B buyers"""

#prepare data for pie chart
a1 = df['Fulfilment'].value_counts()

#step 4: plot the pie chart
fig, ax = plt.subplots()

ax.pie(a1.values, labels=a1.index, autopct='%1.2f%%', Radius=0.7, wedgeprops=dict(width=0.6))
ax.set(aspect='equal')

plt.show()

#plot count of cities by state
plt.figure(figsize=(12,6))
sns.counterplot(data=df,x='ship-state')
plt.xlabel('ship-state')
plt.ylabel('count')
plt.title('Distribution of state')
plt.xticks(rotation=90)
plt.show()

#top_10_States
top_10_state = df['ship-state'].value_counts().head(10)

#plot count of cities by state
plt.figure(figsize=(12,6))
sns.counterplot(data=df[df['ship-state'].isin(top_10_state.index)],x='ship-state')
plt.xlabel('ship-state')
plt.ylabel('count')
plt.title('Distribution of state')
plt.xticks(rotation=45)
plt.show()

"""Note: From above graph you can see that most of the buyers are maharashtra state

**Conclusion**

The data analysis reveals that the business has a significant customer base in maharashtra state, mainly serves retailers, fulfills order through Amazon, experiences high demand for T-shirts and sees M-size as the preferred choice among buyers.
"""



